// This file is generated by Velite

import config from '../velite.config'

type Collections = typeof config.collections

export type Learn = Collections['learn']['schema']['_output']
export declare const learn: Learn[]
