import { CertificateProps } from '../types/certificates';

export const CERTIFICATE: CertificateProps[] = [
  {
    name: 'Alibaba Cloud Certified Developers - 1',
    certificate_url:
      'https://uisiacid-my.sharepoint.com/:i:/g/personal/muhammad_nuha23_student_uisi_ac_id/EXb8PR8yE6dJpnSppXoXFPoBsMOjsAZZ3e9tdS2J1pFgeg?e=g0ET5Y',
    company: 'Alibaba Cloud',
    logo: '/images/certificate/alibaba.png',
    issued: '2024-02-23',
    expired: '2026-02-22',
    credential_id: 'ACCD0119700100007493',
    credential_url: 'https://edu.alibabacloud.com/',
  },
  {
    name: 'Belajar Dasar UX Design',
    certificate_url: 'https://www.dicoding.com/certificates/81P2V6GYOPOY',
    company: 'Dicoding',
    logo: '/images/certificate/dicoding.png',
    issued: '2024-02-18',
    expired: '2027-02-18',
    credential_id: '81P2V6GYOPOY',
    credential_url: 'https://www.dicoding.com/',
  },
  {
    name: 'Belajar Machine Learning untuk Pemula',
    certificate_url: 'https://www.dicoding.com/certificates/JLX12VM6JZ72',
    company: 'Dicoding',
    logo: '/images/certificate/dicoding.png',
    issued: '2024-02-15',
    expired: '2027-02-15',
    credential_id: 'JLX12VM6JZ72',
    credential_url: 'https://www.dicoding.com/',
  },
  {
    name: 'Memulai Pemrograman dengan Python',
    certificate_url: 'https://www.dicoding.com/certificates/NVP7742KWPR0',
    company: 'Dicoding',
    logo: '/images/certificate/dicoding.png',
    issued: '2024-01-24',
    expired: '2027-01-24',
    credential_id: 'NVP7742KWPR0',
    credential_url: 'https://www.dicoding.com/',
  },
  {
    name: 'Belajar Dasar Visualisasi Data',
    certificate_url: 'https://www.dicoding.com/certificates/L4PQQ5L37PO1',
    company: 'Dicoding',
    logo: '/images/certificate/dicoding.png',
    issued: '2024-01-23',
    expired: '2027-01-23',
    credential_id: 'L4PQQ5L37PO1',
    credential_url: 'https://www.dicoding.com/',
  },
  {
    name: 'Python Dasar (Gold)',
    certificate_url:
      'https://badgr.com/public/assertions/tpweNjftQ2-K5hQT7PRGlA',
    company: 'Skilvul',
    logo: '/images/certificate/skilvul.png',
    issued: '2024-02-18',
    expired: '2026-02-18',
    credential_id: '62378UI_UX562022',
    credential_url: 'https://www.rakamin.com/',
  },
  {
    name: 'KKNI Level II in Software Engineering Skill Competency',
    certificate_url: '',
    company: 'BNSP',
    logo: '/images/certificate/bnsp.png',
    issued: '2020-12-03',
    expired: '2023-12-03',
    credential_id: 'No.Reg.TIK.559.00180.2020',
    credential_url: 'https://bnsp.go.id/',
  },
];
